//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuelas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESOR
    {
        public string rut { get; set; }
        public string nombre { get; set; }
        public string titulo { get; set; }
        public string grado { get; set; }
    }
}
